# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1243dd25c5dd73aaab1ab35ab51e3ab"
name = "pageforge"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_content,write_files,write_online_store_pages,write_products,write_themes"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
